export const jackets = [
    {
        name: "Free Spirit",
        price: 120,
        currency: "$",
        image: "../images/Women/woman1.jpg",
        image2: "../images/Women/hiking-woman.jpg",
        image3: "../images/Women/hiking-woman2.jpg",
        image4: "../images/Women/camping-woman.jpg",
        id: "1",
        product_description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
        careAdvice: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr."
    },
    {
        name: "Marine Blue",
        price: 110,
        currency: "$",
        image: "/images/Women/woman2.png",
        id: "2",
    },
    {
        name: "Kobe II",
        price: 80,
        currency: "$",
        image: "/images/Women/woman3.jpg",
        id: "3",
    },
    {
        name: "Nature Lover",
        price: 150,
        currency: "$",
        image: "/images/Women/woman4.jpg",
        id: "4",
    },
    {
        name: "Osaka",
        price: 120,
        currency: "$",
        image: "/images/Women/woman5.jpg",
        id: "5",
    },
    {
        name: "Kobe I",
        price: 75,
        currency: "$",
        image: "/images/Women/woman6.jpg",
        id: "6",
    },
    {
        name: "Urban",
        price: 100,
        currency: "$",
        image: "/images/Women/woman7.jpg",
        id: "7",
    },
    {
        name: "Sam",
        price: 100,
        currency: "$",
        image: "/images/Women/woman8.jpg",
        id: "8",
    },
    {
        name: "Cloud",
        price: 85,
        currency: "$",
        image: "/images/Women/woman9.jpg",
        id: "9",
    }
];